export const proposals = [
  {
    id: 1,
    title: "F10: DAOs <3 smart contracts for skill-acquisition and contribution tracking",
    description: "Develop core Andamio smart contracts for skill-acquisition and contribution tracking",
    href: "https://cardano.ideascale.com/c/idea/1000000",
    status: "Completed",
    year: 2024,
    quarterly: "Q1",
  },
  {
    id: 2,
    title: "F11: Interactive Learning Hub for Smart Contracts",
    description: "Create an engaging platform for learning smart contract development on Cardano using Aiken.",
    href: "https://cardano.ideascale.com/c/idea/1000001",
    status: "In Progress",
    year: 2025,
    quarterly: "Q2",
  },
  {
    id: 3,
    title: "F11: Decentralized Credential Verification System",
    description: "Implement a smart contract-based system for verifying educational credentials on-chain.",
    href: "https://cardano.ideascale.com/c/idea/1000002",
    status: "Proposed",
    year: 2025,
    quarterly: "Q2",
  },
  {
    id: 4,
    title: "F10: NFT-based Learning Certificates",
    description: "Issue NFTs as certificates for completing educational tasks and milestones.",
    href: "https://cardano.ideascale.com/c/idea/1000003",
    status: "Completed",
    year: 2024,
    quarterly: "Q1",
  },
  {
    id: 5,
    title: "F12: Onboarding Platform for Smart Contract Developers",
    description: "Design and launch a beginner-friendly onboarding platform for new Aiken developers.",
    href: "https://cardano.ideascale.com/c/idea/1000004",
    status: "In Progress",
    year: 2025,
    quarterly: "Q3",
  },
  {
    id: 6,
    title: "F12: Contribution Graph for Open-Source Projects",
    description: "Visualize and reward contributions to Cardano open-source projects using Andamio.",
    href: "https://cardano.ideascale.com/c/idea/1000005",
    status: "Approved",
    year: 2025,
    quarterly: "Q3",
  },
  {
    id: 7,
    title: "F11: Gamified Learning Path for Cardano Developers",
    description: "Develop gamified challenges to enhance engagement in learning Cardano smart contracts.",
    href: "https://cardano.ideascale.com/c/idea/1000006",
    status: "Completed",
    year: 2025,
    quarterly: "Q2",
  },
  {
    id: 8,
    title: "F10: Skill Tree Engine for DAOs",
    description: "Build a skill tree engine to map contributor growth and roles in decentralized teams.",
    href: "https://cardano.ideascale.com/c/idea/1000007",
    status: "Completed",
    year: 2024,
    quarterly: "Q1",
  },
  {
    id: 9,
    title: "F12: AI Assistant for Smart Contract Education",
    description: "Integrate AI assistants into the Andamio platform to support self-paced learning.",
    href: "https://cardano.ideascale.com/c/idea/1000008",
    status: "Proposed",
    year: 2025,
    quarterly: "Q3",
  },
  {
    id: 10,
    title: "F11: Community Review Dashboard for Proposals",
    description: "Launch a dashboard to facilitate transparent and community-driven project reviews.",
    href: "https://cardano.ideascale.com/c/idea/1000009",
    status: "Approved",
    year: 2025,
    quarterly: "Q2",
  },
];
